"""
Package for SAP Data Processing schemas
"""
from .schemas import (
    COMPANY_CODE_DATA_SCHEMA,
    MARA_SCHEMA,
    MARC_SCHEMA,
    MBEW_SCHEMA,
    PLANT_DATA_SCHEMA,
    VALUATION_DATA_SCHEMA,
    AFKO_SCHEMA,
    MARA_ORDER_SCHEMA,
    AUFK_SCHEMA,
    AFPO_SCHEMA,
    UNIFIED_SCHEMA,
)
from .schema_hormanization_stats import PROCESS_ORDER_SCHEMA_WITH_RELAVENT_NAMES, LOCAL_MATERIAL_SCHEMA_WITH_RELAVENT_NAMES

__all__ = [
    "MARA_SCHEMA",
    "MBEW_SCHEMA",
    "MARC_SCHEMA",
    "PLANT_DATA_SCHEMA",
    "VALUATION_DATA_SCHEMA",
    "COMPANY_CODE_DATA_SCHEMA",
    "AFKO_SCHEMA",
    "MARA_ORDER_SCHEMA",
    "AUFK_SCHEMA",
    "AFPO_SCHEMA",
    "UNIFIED_SCHEMA",
    "PROCESS_ORDER_SCHEMA_WITH_RELAVENT_NAMES",
    "PROCESS_ORDER_SCHEMA_WITH_RELAVENT_NAMES",
]
