"""
Package for SAP Data Processing schemas
"""
from .schemas import (
    COMPANY_CODE_DATA_SCHEMA,
    MARA_SCHEMA,
    MARC_SCHEMA,
    MBEW_SCHEMA,
    PLANT_DATA_SCHEMA,
    VALUATION_DATA_SCHEMA,
    AFKO_SCHEMA,
    MARA_ORDER_SCHEMA,
    AUFK_SCHEMA,
    AFPO_SCHEMA,
)

__all__ = [
    "MARA_SCHEMA",
    "MBEW_SCHEMA",
    "MARC_SCHEMA",
    "PLANT_DATA_SCHEMA",
    "VALUATION_DATA_SCHEMA",
    "COMPANY_CODE_DATA_SCHEMA",
    "AFKO_SCHEMA",
    "MARA_ORDER_SCHEMA",
    "AUFK_SCHEMA",
    "AFPO_SCHEMA",
]
